/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as LogInRouteImport } from './routes/log-in'
import { Route as MasterPlanRouteImport } from './routes/master-plan'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DashAccountRouteImport } from './routes/_dash.account'
import { Route as DashEventsRouteImport } from './routes/_dash.events'
import { Route as DashHomeRouteImport } from './routes/_dash.home'
import { Route as DashNotesRouteImport } from './routes/_dash.notes'
import { Route as DashTasksRouteImport } from './routes/_dash.tasks'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as NotesIdRouteImport } from './routes/notes.$id'
import { Route as DashAdminAnnouncementsRouteImport } from './routes/_dash.admin.announcements'
import { Route as DashAdminFundsRouteImport } from './routes/_dash.admin.funds'
import { Route as DashAdminHomeRouteImport } from './routes/_dash.admin.home'
import { Route as DashAdminMeetingRouteImport } from './routes/_dash.admin.meeting'
import { Route as DashAdminMembersRouteImport } from './routes/_dash.admin.members'
import { Route as DashAdminMonitoringRouteImport } from './routes/_dash.admin.monitoring'
import { Route as DashAdminSuggestionsRouteImport } from './routes/_dash.admin.suggestions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInRoute = LogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterPlanRoute = MasterPlanRouteImport.update({
  id: '/master-plan',
  path: '/master-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashAccountRoute = DashAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashRoute,
} as any)
const DashEventsRoute = DashEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashRoute,
} as any)
const DashHomeRoute = DashHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashRoute,
} as any)
const DashNotesRoute = DashNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DashRoute,
} as any)
const DashTasksRoute = DashTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashAdminAnnouncementsRoute = DashAdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminFundsRoute = DashAdminFundsRouteImport.update({
  id: '/admin/funds',
  path: '/admin/funds',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminHomeRoute = DashAdminHomeRouteImport.update({
  id: '/admin/home',
  path: '/admin/home',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminMeetingRoute = DashAdminMeetingRouteImport.update({
  id: '/admin/meeting',
  path: '/admin/meeting',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminMembersRoute = DashAdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminMonitoringRoute = DashAdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => DashRoute,
} as any)
const DashAdminSuggestionsRoute = DashAdminSuggestionsRouteImport.update({
  id: '/admin/suggestions',
  path: '/admin/suggestions',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/log-in': typeof LogInRoute
  '/master-plan': typeof MasterPlanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account': typeof DashAccountRoute
  '/events': typeof DashEventsRoute
  '/home': typeof DashHomeRoute
  '/notes': typeof DashNotesRoute
  '/tasks': typeof DashTasksRoute
  '/events/$id': typeof EventsIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/admin/announcements': typeof DashAdminAnnouncementsRoute
  '/admin/funds': typeof DashAdminFundsRoute
  '/admin/home': typeof DashAdminHomeRoute
  '/admin/meeting': typeof DashAdminMeetingRoute
  '/admin/members': typeof DashAdminMembersRoute
  '/admin/monitoring': typeof DashAdminMonitoringRoute
  '/admin/suggestions': typeof DashAdminSuggestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/log-in': typeof LogInRoute
  '/master-plan': typeof MasterPlanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account': typeof DashAccountRoute
  '/events': typeof DashEventsRoute
  '/home': typeof DashHomeRoute
  '/notes': typeof DashNotesRoute
  '/tasks': typeof DashTasksRoute
  '/events/$id': typeof EventsIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/admin/announcements': typeof DashAdminAnnouncementsRoute
  '/admin/funds': typeof DashAdminFundsRoute
  '/admin/home': typeof DashAdminHomeRoute
  '/admin/meeting': typeof DashAdminMeetingRoute
  '/admin/members': typeof DashAdminMembersRoute
  '/admin/monitoring': typeof DashAdminMonitoringRoute
  '/admin/suggestions': typeof DashAdminSuggestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/log-in': typeof LogInRoute
  '/master-plan': typeof MasterPlanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_dash/account': typeof DashAccountRoute
  '/_dash/events': typeof DashEventsRoute
  '/_dash/home': typeof DashHomeRoute
  '/_dash/notes': typeof DashNotesRoute
  '/_dash/tasks': typeof DashTasksRoute
  '/events/$id': typeof EventsIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/_dash/admin/announcements': typeof DashAdminAnnouncementsRoute
  '/_dash/admin/funds': typeof DashAdminFundsRoute
  '/_dash/admin/home': typeof DashAdminHomeRoute
  '/_dash/admin/meeting': typeof DashAdminMeetingRoute
  '/_dash/admin/members': typeof DashAdminMembersRoute
  '/_dash/admin/monitoring': typeof DashAdminMonitoringRoute
  '/_dash/admin/suggestions': typeof DashAdminSuggestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/log-in'
    | '/master-plan'
    | '/sitemap.xml'
    | '/terms'
    | '/account'
    | '/events'
    | '/home'
    | '/notes'
    | '/tasks'
    | '/events/$id'
    | '/notes/$id'
    | '/admin/announcements'
    | '/admin/funds'
    | '/admin/home'
    | '/admin/meeting'
    | '/admin/members'
    | '/admin/monitoring'
    | '/admin/suggestions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/log-in'
    | '/master-plan'
    | '/sitemap.xml'
    | '/terms'
    | '/account'
    | '/events'
    | '/home'
    | '/notes'
    | '/tasks'
    | '/events/$id'
    | '/notes/$id'
    | '/admin/announcements'
    | '/admin/funds'
    | '/admin/home'
    | '/admin/meeting'
    | '/admin/members'
    | '/admin/monitoring'
    | '/admin/suggestions'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/log-in'
    | '/master-plan'
    | '/sitemap.xml'
    | '/terms'
    | '/_dash/account'
    | '/_dash/events'
    | '/_dash/home'
    | '/_dash/notes'
    | '/_dash/tasks'
    | '/events/$id'
    | '/notes/$id'
    | '/_dash/admin/announcements'
    | '/_dash/admin/funds'
    | '/_dash/admin/home'
    | '/_dash/admin/meeting'
    | '/_dash/admin/members'
    | '/_dash/admin/monitoring'
    | '/_dash/admin/suggestions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  LogInRoute: typeof LogInRoute
  MasterPlanRoute: typeof MasterPlanRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  EventsIdRoute: typeof EventsIdRoute
  NotesIdRoute: typeof NotesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in': {
      id: '/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof LogInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-plan': {
      id: '/master-plan'
      path: '/master-plan'
      fullPath: '/master-plan'
      preLoaderRoute: typeof MasterPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/account': {
      id: '/_dash/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof DashAccountRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/events': {
      id: '/_dash/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof DashEventsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/home': {
      id: '/_dash/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashHomeRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/notes': {
      id: '/_dash/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof DashNotesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/tasks': {
      id: '/_dash/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof DashTasksRouteImport
      parentRoute: typeof DashRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/admin/announcements': {
      id: '/_dash/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof DashAdminAnnouncementsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin/funds': {
      id: '/_dash/admin/funds'
      path: '/admin/funds'
      fullPath: '/admin/funds'
      preLoaderRoute: typeof DashAdminFundsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin/home': {
      id: '/_dash/admin/home'
      path: '/admin/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof DashAdminHomeRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin/meeting': {
      id: '/_dash/admin/meeting'
      path: '/admin/meeting'
      fullPath: '/admin/meeting'
      preLoaderRoute: typeof DashAdminMeetingRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin/members': {
      id: '/_dash/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof DashAdminMembersRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin/monitoring': {
      id: '/_dash/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof DashAdminMonitoringRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/admin/suggestions': {
      id: '/_dash/admin/suggestions'
      path: '/admin/suggestions'
      fullPath: '/admin/suggestions'
      preLoaderRoute: typeof DashAdminSuggestionsRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashAccountRoute: typeof DashAccountRoute
  DashEventsRoute: typeof DashEventsRoute
  DashHomeRoute: typeof DashHomeRoute
  DashNotesRoute: typeof DashNotesRoute
  DashTasksRoute: typeof DashTasksRoute
  DashAdminAnnouncementsRoute: typeof DashAdminAnnouncementsRoute
  DashAdminFundsRoute: typeof DashAdminFundsRoute
  DashAdminHomeRoute: typeof DashAdminHomeRoute
  DashAdminMeetingRoute: typeof DashAdminMeetingRoute
  DashAdminMembersRoute: typeof DashAdminMembersRoute
  DashAdminMonitoringRoute: typeof DashAdminMonitoringRoute
  DashAdminSuggestionsRoute: typeof DashAdminSuggestionsRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAccountRoute: DashAccountRoute,
  DashEventsRoute: DashEventsRoute,
  DashHomeRoute: DashHomeRoute,
  DashNotesRoute: DashNotesRoute,
  DashTasksRoute: DashTasksRoute,
  DashAdminAnnouncementsRoute: DashAdminAnnouncementsRoute,
  DashAdminFundsRoute: DashAdminFundsRoute,
  DashAdminHomeRoute: DashAdminHomeRoute,
  DashAdminMeetingRoute: DashAdminMeetingRoute,
  DashAdminMembersRoute: DashAdminMembersRoute,
  DashAdminMonitoringRoute: DashAdminMonitoringRoute,
  DashAdminSuggestionsRoute: DashAdminSuggestionsRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  LogInRoute: LogInRoute,
  MasterPlanRoute: MasterPlanRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  EventsIdRoute: EventsIdRoute,
  NotesIdRoute: NotesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
